#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
#metadata

# use dependencies defined in Modulefile
# modulefile

# A module from the Puppet Forge
# mod 'puppetlabs-stdlib'

# A module from git
# mod 'puppetlabs-ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'

mod 'puppetlabs-java'
mod 'puppetlabs-tomcat'
mod 'garethr-docker'
mod 'jfryman-nginx'
mod 'puppetlabs-mysql'
mod 'puppetlabs-stdlib'
mod 'example42-dovecot'
mod 'thias-postfix'
mod 'thias-mailman'
mod 'thias-php'
mod 'ssm-munin'
mod 'puppetlabs-mongodb'
